### ISSUE TITLE
Ingame usage

### ISSUE THREAD

**Issue by PurplHub** [RobloxArchiver/AssetDownloader#1]
how can I use it in game? and. can it download audios/songs

**Comment by RobloxArchiver** [comment]
Inside of normal game development it cannot be used, to use refer to documetation. (being remade currently) 

And as of now (5/12/2022) Audios and Songs cannot be used as to my knowledge. Give it a try!

**Comment by RobloxArchiver** [comment]
Also if you still have an issue feel free to message me on Discord. 

`RobloxArchiver#2469`
